
IF EXISTS (
		SELECT 1
		FROM SYS.columns
		WHERE NAME = N'USERNAME'
			AND OBJECT_ID = OBJECT_ID(N'dbo.MTS_LOGIN')
		)
BEGIN
	ALTER TABLE MTS_LOGIN ALTER COLUMN USERNAME VARCHAR(150) 
END
GO

IF EXISTS (
		SELECT 1
		FROM SYS.columns
		WHERE NAME = N'EMAIL'
			AND OBJECT_ID = OBJECT_ID(N'dbo.EMPLOYEE')
		)
BEGIN
	ALTER TABLE EMPLOYEE ALTER COLUMN EMAIL VARCHAR(150)  
END
GO

IF EXISTS (
		SELECT 1
		FROM SYS.columns
		WHERE NAME = N'EMAIL'
			AND OBJECT_ID = OBJECT_ID(N'dbo.MTS_USERCONTACTS')
		)
BEGIN
	ALTER TABLE MTS_USERCONTACTS ALTER COLUMN EMAIL VARCHAR(150) 
END
GO