//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS.Login.Views.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logon_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logon_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTS.Login.Views.App_LocalResources.Logon.cshtml", typeof(Logon_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin locked.
        /// </summary>
        public static string ADMIN_LOCK {
            get {
                return ResourceManager.GetString("ADMIN_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous attempt.
        /// </summary>
        public static string ANON_ATTEMPT {
            get {
                return ResourceManager.GetString("ANON_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string AUTH_FAIL {
            get {
                return ResourceManager.GetString("AUTH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string FORGET_PASS {
            get {
                return ResourceManager.GetString("FORGET_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTS_UserPasswordEmail.
        /// </summary>
        public static string ForgotEmailSpName {
            get {
                return ResourceManager.GetString("ForgotEmailSpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string ForgotEmailTemplateId {
            get {
                return ResourceManager.GetString("ForgotEmailTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password..
        /// </summary>
        public static string INVALID_CUR_PASS {
            get {
                return ResourceManager.GetString("INVALID_CUR_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id..
        /// </summary>
        public static string INVALID_USERNAME {
            get {
                return ResourceManager.GetString("INVALID_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LOGIN_FAIL {
            get {
                return ResourceManager.GetString("LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time login user can&apos;t use ForgetPassword.
        /// </summary>
        public static string NEW_USER_BLOCK_RESET_PASS {
            get {
                return ResourceManager.GetString("NEW_USER_BLOCK_RESET_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password should not be equal to CurrentPassword..
        /// </summary>
        public static string NewPassword_should_not_be_equal_to_CurrentPassword {
            get {
                return ResourceManager.GetString("NewPassword should not be equal to CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password already used.
        /// </summary>
        public static string PASS_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PASS_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string PASS_CHNG_SUCCESS {
            get {
                return ResourceManager.GetString("PASS_CHNG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password expired.
        /// </summary>
        public static string PASS_EXPIRED {
            get {
                return ResourceManager.GetString("PASS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password sent your mail id.
        /// </summary>
        public static string PASS_SENT {
            get {
                return ResourceManager.GetString("PASS_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sec Question or answer you entered is incorrect..
        /// </summary>
        public static string SEC_ANS_WRONG {
            get {
                return ResourceManager.GetString("SEC_ANS_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User locked for no of attempts.
        /// </summary>
        public static string USER_LOCK {
            get {
                return ResourceManager.GetString("USER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and New Password should not be same..
        /// </summary>
        public static string USER_PASS_NOT_SAME {
            get {
                return ResourceManager.GetString("USER_PASS_NOT_SAME", resourceCulture);
            }
        }
    }
}
